# **NumPy Fundamentals**

NumPy (Numerical Python) is a fundamental Python library for numerical computing and data analysis.

This notebook introduces the core concepts of NumPy arrays and demonstrates how NumPy can be used for numerical operations, array manipulation, statistics, and practical data analysis.

#### **Learning Objectives**

By the end of this notebook, you will be able to:

- Understand NumPy arrays
- Create 1-D, 2-D, and multi-dimensional arrays
- Understand array dimensions, shape, size, and data types
- Access and slice array elements
- Perform arithmetic and scalar operations
- Use mathematical and statistical functions
- Reshape and flatten arrays
- Generate random numbers
- Understand the importance of NumPy in data analysis and machine learning

#### **1. Import NumPy**

In [1]:
import numpy as np

#### **2. Creating a One-Dimensional Array**

In [2]:
numbers = np.array([10, 20, 30, 40, 50, 60])
print(numbers)

[10 20 30 40 50 60]


#### **3. Creating a Two-Dimensional Array**

In [3]:
number = np.array([[1,2,3],[4,5,6],[1,2,3]])
print(number)

[[1 2 3]
 [4 5 6]
 [1 2 3]]


#### **4. Creating a Three-Dimensional Array**

In [4]:
array_3d = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]],
    [[1, 2, 3], [4, 5, 6]]
])

print(array_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[ 1  2  3]
  [ 4  5  6]]]


#### **5. Creating Arrays with Built-in NumPy Functions**

In [5]:
# 1-D Zeros Array
print(np.zeros(4))

[0. 0. 0. 0.]


In [6]:
# 2-D Zeros Array
print(np.zeros((3,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
# 1-D Ones Array
print(np.ones(5))

[1. 1. 1. 1. 1.]


In [8]:
# 2-D Ones Array
print(np.ones((5,7)))

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [9]:
# 2-D identity matrix
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### **6. Array Attributes**
- ndim
- shape
- size
- dtype  

##### **6.1 ndim Attribute**
The `ndim` attribute returns the number of dimensions of an array.

In [10]:
student_marks = np.array([85, 78, 92, 88, 95]) 
print(student_marks)
print("Dimension of Array is = ",student_marks.ndim)

[85 78 92 88 95]
Dimension of Array is =  1


In [11]:
student_marks = np.array([[85, 78, 92], [88, 95, 81]]) 
print(student_marks)
print("Dimension of Array is = ",student_marks.ndim) 

[[85 78 92]
 [88 95 81]]
Dimension of Array is =  2


##### **6.2 shape Attribute**
The `shape` attribute returns the size of an array along each dimension.

For a 2-D array, it is represented as: `(rows, columns)`

In [12]:
student_marks = np.array([[85, 78, 92,20,40], [88, 95, 81,40,8],[88, 95, 81,40,50]]) 
student_marks.shape

(3, 5)

##### **6.3 size Attribute**
The `size` attribute returns the total number of elements in an array. 

In [13]:
student_marks = np.array([[85, 78, 92,20,40], [88, 95, 81,40,50],[88, 95, 81,40,50]]) 
student_marks.size

15

##### **6.4 dtype Attribute**
The `dtype` attribute returns the data type of the elements stored in an array. 

In [14]:
student_marks = np.array([[85, 78, 92,20,40], [88, 95, 81,40,50],[88, 95, 81,40,50]]) 
student_marks.dtype

dtype('int64')

#### **7. Indexing & Slicing**
Each element in NumPy array has an index. `The first element has an index of 0` While `The second element has an index of 1, and so on.`

##### **7.1 Indexing 1-D Array**

In [15]:
student_marks = np.array([85, 78, 92, 88, 95]) 
print(student_marks[0]) 
print(student_marks[2]) 
print(student_marks[4]) 

85
92
95


> **Negative indexing**

Negative indexing starts from the end of the array.
- `-1` refers to the last element,
- `-2` refers to the second last element
- `-3` refers to the third last element.  

In [16]:
student_marks = np.array([85, 78, 92, 88, 95]) 
print(student_marks[-1]) 
print(student_marks[-2])

95
88


##### **7.2 slicing 1-D Array**
Slicing is used to retrieve a range of elements from an array.

`array[start:stop:step]`

In [17]:
student_marks = np.array([85, 78, 92, 88, 95])

# Here we will give two index, first one is include while 2nd one is exclude
# Means if [3:5], it means start from 3 till to 4, means 5 is exclude
print(student_marks[3:5])

[88 95]


In [18]:
student_marks = np.array([85, 78, 92, 88, 95]) 
print(student_marks[2:]) 

[92 88 95]


In [19]:
numbers = np.array([10, 20, 30, 40, 50, 60])

# Here the 3rd value show us step
print(numbers[0:6:2]) 

[10 30 50]


##### **7.3 Indexing 2-D arrays**
`2-D array consists of rows and columns. To access an element, specify the row index followed by the column index.`

In [20]:
student_marks = np.array([[85, 78, 92],[88, 95, 81]]) 
print(student_marks[0,1]) 
print(student_marks[1,2])

78
81


##### **7.4 Slicing 2-D arrays**

In [21]:
student_marks = np.array([[85, 78, 92],[88, 95, 81]]) 
print(student_marks[:,1:]) 

[[78 92]
 [95 81]]


In [22]:
student_marks = np.array([[85, 78, 92,98],[88, 95, 81,90],[1,2,3,4],[5,6,7,8]]) 
print(student_marks)

[[85 78 92 98]
 [88 95 81 90]
 [ 1  2  3  4]
 [ 5  6  7  8]]


In [23]:
print(student_marks[1:,2:]) 

[[81 90]
 [ 3  4]
 [ 7  8]]


##### **7.5 Boolean Indexing and Filtering**

In [24]:
marks = np.array([45, 67, 82, 39, 91])

passed_marks = marks[marks >= 50]

print(passed_marks)

[67 82 91]


##### **8. Changing Data Types**

In [25]:
marks = np.array([85, 90, 75])

marks_float = marks.astype(float)

print(marks_float)
print(marks_float.dtype)

[85. 90. 75.]
float64


##### **9. Combining Arrays**

`concatenate()`

In [26]:
array1 = np.array([10, 20, 30])
array2 = np.array([40, 50, 60])

combined = np.concatenate((array1, array2))

print(combined)

[10 20 30 40 50 60]


#### **10. Array Operation**
`Addition`, `Subtraction`, `Multiplication`, `Division`

In [27]:
# Addition
sales_january = np.array([12000, 15000, 18000]) 
sales_february = np.array([10000, 16000, 17000]) 
total_sales = sales_january + sales_february 
print(total_sales)

[22000 31000 35000]


In [28]:
# Subtraction
planned_sales = np.array([15000, 18000, 20000]) 
actual_sales = np.array([14000, 17000, 19500]) 
difference = planned_sales - actual_sales 
print(difference) 

[1000 1000  500]


In [29]:
# Multiplication
quantity = np.array([5, 8, 10]) 
price = np.array([200, 150, 100]) 
total_amount = quantity * price 
print(total_amount) 

[1000 1200 1000]


In [30]:
# Division
obtained_marks = np.array([420, 450, 470]) 
total_marks = np.array([500, 500, 500]) 
percentage = (obtained_marks / total_marks) * 100 
print(percentage) 

[84. 90. 94.]


#### **11. Broadcasting**

Broadcasting allows NumPy to perform operations between arrays and compatible values or shapes without explicitly repeating the data.

In [31]:
marks = np.array([70, 75, 80])

bonus = 5

updated_marks = marks + bonus

print(updated_marks)

[75 80 85]


#### **12. Scalar operations**
`A scalar is a single value. NumPy allows you to perform operations between an array and a single 
value.`

In [32]:
# Add a Scalar value
marks = np.array([70, 75, 80]) 
updated_marks = marks + 5 
print(updated_marks) 

[75 80 85]


In [33]:
# Multiply a scalar
salary = np.array([30000, 35000, 40000]) 
updated_salary = salary * 1.10 
print(updated_salary) 

[33000. 38500. 44000.]


In [34]:
# Divide by a scalar value
salary = np.array([30000, 35000, 40000]) 
updated_salary = salary / 5
print(updated_salary) 

[6000. 7000. 8000.]


In [35]:
# Subtract a scalar value
salary = np.array([30000, 35000, 40000]) 
updated_salary = salary - 5000
print(updated_salary) 

[25000 30000 35000]


In [36]:
# Practical Example
obtained_marks = np.array([425, 450, 475]) 
total_marks = 500 
percentage = (obtained_marks / total_marks) * 100 
print("Obtained Marks:", obtained_marks) 
print("Percentage:", percentage) 

Obtained Marks: [425 450 475]
Percentage: [85. 90. 95.]


#### **13. Mathematical and Statistical Functions**

##### **13.1 Sum()**

In [37]:
marks = np.array([85, 78, 92, 88, 95]) 
print(np.sum(marks)) 

438


##### **13.2 Mean()**

In [38]:
# The mean is one of the most commonly used function
marks = np.array([85, 78, 92, 88, 95]) 
print(np.mean(marks))

87.6


In [39]:
a=np.array([10,20,30,40,50,60,70,80,90,100,200,400,500])
print(np.mean(a))

126.92307692307692


##### **13.3 Median()**

In [40]:
marks = np.array([85, 78, 92, 88, 95]) 
print(np.median(marks)) 

88.0


##### **13.4 Min()**

In [41]:
marks = np.array([85, 78, 92,87, 88, 95]) 
print(np.min(marks))

78


##### **13.5 Max()**

In [42]:
marks = np.array([85, 78, 92, 88, 95,100]) 
print(np.max(marks)) 

100


##### **13.6 std()**
`std() calculates the standard deviation, which measures how much the values vary from the average.`

`A small standard deviation indicates that the values are close to the mean` While `large standard deviation indicates greater variation.`

In [43]:
marks = np.array([85, 78, 92, 88, 95,80,82,75,70,72])
print(np.std(marks)) 

7.912648102879339


In [44]:
marks = np.array([85, 78, 92, 88, 95,80,82,75,70,72]) 
print(np.mean(marks)) 

81.7


In [45]:
marks = np.array([85, 78, 92, 88, 95,65,55,50,70,60]) 
print(np.std(marks))

15.256474035634842


In [46]:
marks = np.array([85, 78, 92, 88, 95,65,55,50,70,60]) 
print(np.mean(marks)) 

73.8


##### **13.7 var()**

The var() function calculates the variance of a dataset.
- Variance measures the average squared deviation from the mean.
- Standard deviation is the square root of variance.
- Variance is the square of standard deviation.

In [47]:
marks = np.array([85, 78, 92, 88, 95,80,82,75,70,72])
var1= np.var(marks)
print(var1)

62.61


In [48]:
marks = np.array([85, 78, 92, 88, 95,65,55,50,70,60])
var2 = np.var(marks)
print(var2) 

232.76000000000005


##### **13.8 percentile()**

used to compute the q-th percentile of a dataset or along a specified array axis

This becomes useful later for:
- quartiles
- IQR
- outlier detection

In [49]:
marks = np.array([55, 60, 65, 70, 75, 80, 85, 90, 95])

print(np.percentile(marks, 25))
print(np.percentile(marks, 50))
print(np.percentile(marks, 75))

65.0
75.0
85.0


#### **14. Working with Array Axes**

`axis=0 → operation down the rows / column-wise`

In [50]:
marks = np.array([
    [80, 75, 90],
    [70, 85, 95],
    [88, 92, 84]
])

print(np.sum(marks))
print("Axis = 0")
print(np.sum(marks, axis=0))

759
Axis = 0
[238 252 269]


`axis=1 → operation across the columns / row-wise`

In [51]:
marks = np.array([
    [80, 75, 90],
    [70, 85, 95],
    [88, 92, 84]
])

print("Axis = 1")
print(np.sum(marks, axis=1))

Axis = 1
[245 250 264]


#### **15. Reshaping Array**

##### **15.1 reshape()**

`The reshape() function changes the dimensions of an array while keeping the same data. The total number of elements must remain the same before and after reshaping.`

In [52]:
numbers = np.array([10, 20, 30, 40, 50, 60]) 
new_array = numbers.reshape(2, 3) 
print(new_array) 

[[10 20 30]
 [40 50 60]]


In [53]:
numbers = np.array([10, 20, 30, 40, 50, 60])
print("1-D Array is = ",numbers)
new_array = numbers.reshape(3, 2) 
print(new_array) 

1-D Array is =  [10 20 30 40 50 60]
[[10 20]
 [30 40]
 [50 60]]


#### **15.2 `flatten()` vs `ravel()`**

Both can convert a multi-dimensional array into a one-dimensional array.

`flatten()` returns a copy.

`ravel()` generally returns a view when possible.

> Flatten()

In [54]:
# Create a numpy array
a = np.array([(1,2,3,4),(3,1,4,2)])

# Let's print the array a
print ("Original array:\n ", a)

print("===========================")

# Convert nd array to 1D array
c = a.flatten()

# Flatten passes copy of original array to 'c'
print ("\nFlatten array using flatten: ", c)

Original array:
  [[1 2 3 4]
 [3 1 4 2]]

Flatten array using flatten:  [1 2 3 4 3 1 4 2]


In [55]:
# Changed the Value of the Copied Array but it will not make changes in the origonal Array
c[2] = 33

print ("Flatten array: ", c)

# Let's print the array a
print ("\nOriginal array:\n ", a)

Flatten array:  [ 1  2 33  4  3  1  4  2]

Original array:
  [[1 2 3 4]
 [3 1 4 2]]


> Ravel()

In [56]:
import numpy as np

# Create a numpy array
a = np.array([(1,2,3,4),(3,1,4,2)])

# Let's print the array a
print ("Original array:\n ", a)

ra = np.ravel(a)
print ("\nFlatten array using ravel: ", ra)

Original array:
  [[1 2 3 4]
 [3 1 4 2]]

Flatten array using ravel:  [1 2 3 4 3 1 4 2]


In [57]:
# Changed the Value of the Copied Array but it will also make changes in the origonal Array, as we use Ravel()
ra[3] = 44

print ("Flatten array: ", ra)

# Let's print the array a
print ("\nOriginal array:\n ", a)

Flatten array:  [ 1  2  3 44  3  1  4  2]

Original array:
  [[ 1  2  3 44]
 [ 3  1  4  2]]


#### **16. Random Numbers**
- rand()
- randint()
- seed()  

> rand() Function 
> * The rand() function generates random decimal numbers between 0 and 1.

In [58]:
# 1-D Array
random_numbers = np.random.rand(10) 
print(random_numbers) 

[0.91359106 0.18087049 0.99562097 0.2772443  0.37548545 0.05427278
 0.95977963 0.47582422 0.32173684 0.57569474]


In [59]:
# 2-D Array
data = np.random.rand(2, 3)
print(data) 

[[0.67290854 0.47239632 0.17540072]
 [0.67113156 0.4906951  0.07914971]]


> randint() Function 
> * The randint() function generates random integers within a specified range. 

In [60]:
# np.random.randint(start, stop, size) 
marks = np.random.randint(50, 101, 10) 
print(marks) 

[73 59 95 88 58 58 72 78 92 88]


> seed() Function 

Normally, random numbers change every time a program is executed.

The seed() function fixes the starting point of the random number generator, allowing the same random numbers to be generated every time.

In [61]:
np.random.seed(42) 
marks = np.random.randint(50, 101, 5) 
print(marks) 

[88 78 64 92 57]


In [62]:
np.random.seed(43) 
marks = np.random.randint(50, 101, 5) 
print(marks) 

[54 50 99 71 66]


In [63]:
# As i Use again but given same values as above
np.random.seed(42) 
marks = np.random.randint(50, 101, 5) 
print(marks)

[88 78 64 92 57]


#### **17. Practical Data Analysis Example**

Suppose we have the marks of students in three subjects.

In [64]:
marks = np.array([
    [85, 78, 92],
    [88, 95, 81],
    [76, 84, 89],
    [90, 87, 93]
])

print("Total Marks:", np.sum(marks, axis=1))
print("Average Marks:", np.mean(marks, axis=1))
print("Highest Mark:", np.max(marks))
print("Lowest Mark:", np.min(marks))

Total Marks: [255 264 249 270]
Average Marks: [85. 88. 83. 90.]
Highest Mark: 95
Lowest Mark: 76


This example demonstrates how NumPy can be used to perform fast numerical calculations on structured data.

#### **18. Summary**

In this notebook, we learned:

- What NumPy is
- How to create NumPy arrays
- One-dimensional, two-dimensional, and multi-dimensional arrays
- Array attributes such as `ndim`, `shape`, `size`, and `dtype`
- Indexing and slicing
- Boolean indexing and filtering
- Changing Data Types
- Combining Array
- Arithmetic operations
- Scalar operations
- Mathematical and statistical functions
- Reshaping and flattening
- Random number generation
- Practical numerical analysis with NumPy

NumPy provides the numerical foundation for many Python-based data analysis, machine learning, and scientific computing libraries.