#### Import Numpy

In [1]:
import numpy as np

> How to create one dimension Array

In [2]:
numbers = np.array([10, 20, 30, 40, 50, 60])
print(numbers)

[10 20 30 40 50 60]


> How to create Two dimension Array

In [3]:
number = np.array([[1,2,3],[4,5,6],[1,2,3]])
print(number)

[[1 2 3]
 [4 5 6]
 [1 2 3]]


> How to create Three dimension Array

In [4]:
di = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[1,2,3],[4,5,6]]])
print(di)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[ 1  2  3]
  [ 4  5  6]]]


In [5]:
print(np.zeros(4))

[0. 0. 0. 0.]


In [6]:
print(np.zeros((3,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [58]:
print(np.ones(5))

[1. 1. 1. 1. 1.]


In [7]:
print(np.ones((5,7)))

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [8]:
print(np.eye(3,3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [60]:
print(np.arange(1,11))

[ 1  2  3  4  5  6  7  8  9 10]


In [9]:
print(np.arange(1,11,2))

[1 3 5 7 9]


### Array Attributes
> * ndim
> * shape
> * size
> * dtype  

##### ndim Attribute
> The ndim attribute returns the number of dimensions of an array.

In [10]:
student_marks = np.array([85, 78, 92, 88, 95]) 
print(student_marks)
print("Dimension of Array is = ",student_marks.ndim)

[85 78 92 88 95]
Dimension of Array is =  1


In [11]:
student_marks = np.array([[85, 78, 92], [88, 95, 81]]) 
print(student_marks)
print("Dimension of Array is = ",student_marks.ndim) 

[[85 78 92]
 [88 95 81]]
Dimension of Array is =  2


##### shape Attribute
> The shape attribute returns the number of rows and columns in an array. 

In [12]:
student_marks = np.array([[85, 78, 92,20,40], [88, 95, 81,40,8],[88, 95, 81,40,50]]) 
student_marks.shape

(3, 5)

##### size Attribute
> The size attribute returns the total number of elements in an array. 

In [13]:
student_marks = np.array([[85, 78, 92,20,40], [88, 95, 81,40,50],[88, 95, 81,40,50]]) 
student_marks.size

15

##### dtype Attribute 
> The dtype attribute returns the data type of the elements stored in an array. 

In [66]:
student_marks = np.array([[85, 78, 92,20,40], [88, 95, 81,40,50],[88, 95, 81,40,50]]) 
student_marks.dtype

dtype('int64')

##### Indexing and Slicing
Each element in NumPy array has an index.
* The first element has an index of 0
* The second element has an index of 1, and so on. 

In [67]:
student_marks = np.array([85, 78, 92, 88, 95]) 
print(student_marks[0]) 
print(student_marks[2]) 
print(student_marks[4]) 

85
92
95


> Negative indexing 
> > Negative indexing starts from the end of the array.
> * -1 refers to the last element,
> * -2 refers to the second last element
> * and -3 refers to the third last element.  

In [68]:
student_marks = np.array([85, 78, 92, 88, 95]) 
print(student_marks[-1]) 
print(student_marks[-2])

95
88


##### Array slicing 
Slicing is used to retrieve a range of elements from an array.

##### Slicing 1-D Array

In [69]:
student_marks = np.array([85, 78, 92, 88, 95]) 
print(student_marks[:3])

[85 78 92]


In [70]:
student_marks = np.array([85, 78, 92, 88, 95]) 
print(student_marks[2:]) 

[92 88 95]


In [71]:
numbers = np.array([10, 20, 30, 40, 50, 60]) 
print(numbers[0:6:2]) 

[10 30 50]


##### 2-D Array

> Indexing 2-D arrays
* 2-D array consists of rows and columns. To access an element, specify the row index followed by the column index. 

In [ ]:
student_marks = np.array([[85, 78, 92],[88, 95, 81]]) 
print(student_marks[0,1]) 
print(student_marks[1,2]) 

78
81


> Slicing 2-D arrays
* Slicing can also be applied to 2-D arrays. 

In [73]:
student_marks = np.array([[85, 78, 92],[88, 95, 81]]) 
print(student_marks[:,1:]) 

[[78 92]
 [95 81]]


In [74]:
student_marks = np.array([[85, 78, 92,98],[88, 95, 81,90],[1,2,3,4],[5,6,7,8]]) 
print(student_marks)

[[85 78 92 98]
 [88 95 81 90]
 [ 1  2  3  4]
 [ 5  6  7  8]]


In [75]:
print(student_marks[1:,2:]) 

[[81 90]
 [ 3  4]
 [ 7  8]]


##### Array Operation
* Addition
* Subtraction
* Multiplication
* Division

In [76]:
# Addition
sales_january = np.array([12000, 15000, 18000]) 
sales_february = np.array([10000, 16000, 17000]) 
total_sales = sales_january + sales_february 
print(total_sales)

[22000 31000 35000]


In [77]:
# Subtraction
planned_sales = np.array([15000, 18000, 20000]) 
actual_sales = np.array([14000, 17000, 19500]) 
difference = planned_sales - actual_sales 
print(difference) 

[1000 1000  500]


In [78]:
# Multiplication
quantity = np.array([5, 8, 10]) 
price = np.array([200, 150, 100]) 
total_amount = quantity * price 
print(total_amount) 

[1000 1200 1000]


In [79]:
# Division
obtained_marks = np.array([420, 450, 470]) 
total_marks = np.array([500, 500, 500]) 
percentage = (obtained_marks / total_marks) * 100 
print(percentage) 

[84. 90. 94.]


##### Scalar operations 
> A scalar is a single value. NumPy allows you to perform operations between an array and a single 
value.

In [80]:
# Adding Scalar
marks = np.array([70, 75, 80]) 
updated_marks = marks + 5 
print(updated_marks) 

[75 80 85]


In [81]:
# Multiplying by a scalar
salary = np.array([30000, 35000, 40000]) 
updated_salary = salary * 1.10 
print(updated_salary) 

[33000. 38500. 44000.]


In [82]:
# Divide by a scalar
salary = np.array([30000, 35000, 40000]) 
updated_salary = salary / 5
print(updated_salary) 

[6000. 7000. 8000.]


In [83]:
# Subtract a scalar
salary = np.array([30000, 35000, 40000]) 
updated_salary = salary - 5000
print(updated_salary) 

[25000 30000 35000]


In [84]:
# Practical Example
obtained_marks = np.array([425, 450, 475]) 
total_marks = 500 
percentage = (obtained_marks / total_marks) * 100 
print("Obtained Marks:", obtained_marks) 
print("Percentage:", percentage) 

Obtained Marks: [425 450 475]
Percentage: [85. 90. 95.]


##### Mathematical and Statistical Functions 

> Sum() Function

In [85]:
marks = np.array([85, 78, 92, 88, 95]) 
print(np.sum(marks)) 

438


> Mean() Function 

In [86]:
# The mean is one of the most commonly used function
marks = np.array([85, 78, 92, 88, 95]) 
print(np.mean(marks)) 

87.6


> Median() Function 

In [87]:
marks = np.array([85, 78, 92, 88, 95]) 
print(np.median(marks)) 

88.0


> Min() Function 

In [14]:
marks = np.array([85, 78, 92,87, 88, 95]) 
print(np.min(marks))

78


> Max() Function

In [16]:
marks = np.array([85, 78, 92, 88, 95,100]) 
print(np.max(marks)) 

100


In [17]:
a=np.array([10,20,30,40,50,60,70,80,90,100,200,400,500])
print(np.mean(a))

126.92307692307692


> std() Function 
> * The std() function calculates the standard deviation, which measures how much the values vary from the average.
> * A small standard deviation indicates that the values are close to the mean
> * while a large standard deviation indicates greater variation. 

In [19]:
marks = np.array([85, 78, 92, 88, 95,80,82,75,70,72])
print(np.std(marks)) 

7.912648102879339


In [21]:
# marks = np.array([85, 78, 92, 88, 95,80,82,75,70,72]) 
# print(np.mean(marks)) 

In [22]:
marks = np.array([85, 78, 92, 88, 95,65,55,50,70,60]) 
print(np.std(marks)) 

15.256474035634842


In [24]:
# marks = np.array([85, 78, 92, 88, 95,65,55,50,70,60]) 
# print(np.mean(marks)) 

> var() Function 
> * The var() function calculates the variance of a dataset.
> * Variance measures how far the values are spread from the mean. It is closely related to standard deviation.
> * square root of VAR is equal to STD
> * Power 2 of STD is variance

In [25]:
marks = np.array([85, 78, 92, 88, 95,80,82,75,70,72])
var1= np.var(marks)
print(var1) 

62.61


In [26]:
marks = np.array([85, 78, 92, 88, 95,65,55,50,70,60])
var2 = np.var(marks)
print(var2) 

232.76000000000005


##### Reshaping Array
> * reshape()  
> * flatten()  

> The reshape() function changes the dimensions of an array while keeping the same data. The total number of elements must remain the same before and after reshaping. 

In [27]:
numbers = np.array([10, 20, 30, 40, 50, 60]) 
new_array = numbers.reshape(2, 3) 
print(new_array) 

[[10 20 30]
 [40 50 60]]


In [28]:
numbers = np.array([10, 20, 30, 40, 50, 60])
print("1-D Array is = ",numbers)
new_array = numbers.reshape(3, 2) 
print(new_array) 

1-D Array is =  [10 20 30 40 50 60]
[[10 20]
 [30 40]
 [50 60]]


> flatten() Function
> * The flatten() function converts a multi-dimensional array into a one-dimensional array. 

In [29]:
student_marks = np.array([
[85, 78, 92], 
[88, 95, 81] 
]) 
new_array = student_marks.flatten()
print("Old Array is")
print(student_marks)

print("----------")

print("New Array is")
print(new_array) 

Old Array is
[[85 78 92]
 [88 95 81]]
----------
New Array is
[85 78 92 88 95 81]


##### Random Numbers
> * rand()
> * randint()
> * seed()  

> rand() Function 
> * The rand() function generates random decimal numbers between 0 and 1.

In [34]:
# 1-D Array
random_numbers = np.random.rand(10) 
print(random_numbers) 

[0.14923008 0.04949467 0.07406388 0.5975985  0.27654175 0.80635074
 0.42046158 0.64814769 0.97342606 0.75193865]


In [37]:
# 2-D Array
data = np.random.rand(2, 3) 
print(data) 

[[0.09880174 0.07368661 0.13436893]
 [0.4098539  0.64205556 0.59532241]]


> randint() Function 
> * The randint() function generates random integers within a specified range. 

In [40]:
# np.random.randint(start, stop, size) 
marks = np.random.randint(50, 101, 10) 
print(marks) 

[96 81 61 55 71 86 64 66 73 90]


> seed() Function 
> * Normally, random numbers change every time a program is executed.
> * The seed() function fixes the starting point of the random number generator, allowing the same random numbers to be generated every time.

In [ ]:
np.random.seed(1) 
marks = np.random.randint(50, 101, 5) 
print(marks) 

[87 93 62 58 59]


In [48]:
np.random.seed(2) 
marks = np.random.randint(50, 101, 5) 
print(marks) 

[90 65 95 58 72]
